[package]
name = "settings-schema-derive"
version = "0.3.0"
authors = ["Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
darling = "0.12"
proc-macro2 = "1"
quote = "1"
syn = "1"
