[package]
name = "alvr_launcher"
version = "13.1.0"
authors = ["Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
semver = "0.11"
serde_json = "1"
fs_extra = "1"
tempfile = "3"
alcro = "0.4"
alvr_common = { path = "../common" }
single-instance = "0.1"
self_update = { version = "0.22", features = ["archive-zip"] }
reqwest = "0.10"
zip = "0.5"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
