[package]
name = "alvr_launcher"
version = "15.0.0"
authors = ["alvr-org", "Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
semver = "0.11"
serde_json = "1"
alvr_common = { path = "../common" }
single-instance = "0.3"
druid = "0.7"
ureq = "2"
sysinfo = "0.16"

[target.'cfg(windows)'.dependencies]
winreg = "0.8"

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.9"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
