[package]
name = "alvr_filesystem-layout"
version = "15.2.1"
authors = ["alvr-org", "Patrick Nicolas <patricknicolas@laposte.net>"]
license = "MIT"
edition = "2018"

[dependencies]
lazy_static = "1"
dirs = "1.0.5"
