[workspace]
resolver = "2"
members = [
    "alvr/settings-schema-derive",
    "alvr/settings-schema",
    "alvr/openvr-driver-sys",
    "alvr/filesystem",
    "alvr/common",
    "alvr/commands",
    "alvr/session",
    "alvr/sockets",
    "alvr/audio",
    "alvr/client",
    "alvr/server",
    "alvr/launcher",
    "alvr/vrcompositor-wrapper",
    "alvr/vulkan-layer",
    "alvr/xtask",
    "alvr/experiments/client",     # needed for bug in cargo-subcommand
    "alvr/experiments/*",
]

[patch.crates-io]
# wgpu version that works both with rend3 and alvr_graphics vulkan interop
wgpu = { git = "https://github.com/zarik5/wgpu", rev = "c9fe5819c1f07782dceae80d0306abf0f6e2de51" }
wgpu-hal = { git = "https://github.com/zarik5/wgpu", rev = "c9fe5819c1f07782dceae80d0306abf0f6e2de51" }
wgpu-types = { git = "https://github.com/zarik5/wgpu", rev = "c9fe5819c1f07782dceae80d0306abf0f6e2de51" }
ndk-glue = { git = "https://github.com/rust-windowing/android-ndk-rs" }
