[workspace]
members = [
    "alvr/settings-schema-derive",
    "alvr/settings-schema",
    "alvr/openvr-driver-sys",
    "alvr/xtask",
    "alvr/common",
    "alvr/client",
    "alvr/server",
    "alvr/dashboard",
    "alvr/launcher",
    "alvr/vulkan-layer",
]
