[package]
name = "alvr_client"
version = "14.1.0"
authors = ["alvr-org", "Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2018"

[lib]
crate_type = ["staticlib", "cdylib"]

[features]
default = []
build-cpp = []

[dependencies]
parking_lot = "0.11"
lazy_static = "1"
log = "0.4"
serde_json = "1"
settings-schema = { path = "../settings-schema" }
alvr_common = { path = "../common" }
nalgebra = "0.24"
futures = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

# todo: move to target_os = "android"
jni = "0.18"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.9"

[build-dependencies]
walkdir = "2"
cc = { version = "1", features = ["parallel"] }
bindgen = "0.56"
