[package]
name = "alvr_client"
version = "15.1.0"
authors = ["alvr-org", "Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2018"

[lib]
crate_type = ["staticlib", "cdylib"]

[features]
default = []
build-cpp = []

[dependencies]
parking_lot = "0.11"
lazy_static = "1"
log = "0.4"
serde = "1"
serde_json = "1"
bincode = "1"
settings-schema = { git = "https://github.com/alvr-org/ALVR", rev = "08708f19b2ec70264e2ba2b0adfaa64bd96489bd" }
alvr_common = { path = "../common" }
nalgebra = "0.25"
futures = "0.3"
bytes = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
rand = "0.8"
cpal = "0.13"

# todo: move to target_os = "android"
jni = "0.19"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.10"
# todo: use CPAL when moving the entry point to Rust
oboe = "0.4" # Note: cannot use feature "java-interface" to query audio info

[build-dependencies]
walkdir = "2"
cc = { version = "1", features = ["parallel"] }
bindgen = "0.57"
