[package]
name = "alvr_session"
version = "16.0.0"
authors = ["alvr-org", "Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2021"
rust-version = "1.56"

[dependencies]
alvr_common = { path = "../common" }

bytemuck = { version = "1", features = ["derive"] }
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
settings-schema = { path = "../settings-schema", features = [
    "rename_camel_case",
] }
