[package]
name = "vrcompositor-wrapper"
version = "17.0.0-dev.6"
authors = ["alvr-org", "Patrick Nicolas <patricknicolas@laposte.net>"]
license = "MIT"
edition = "2021"
rust-version = "1.58"

[dependencies]
exec = "0.3.1"
