[package]
name = "vrcompositor-wrapper"
version = "16.0.0"
authors = ["alvr-org", "Patrick Nicolas <patricknicolas@laposte.net>"]
license = "MIT"
edition = "2021"
rust-version = "1.56"

[dependencies]
exec = "0.3.1"
