[package]
name = "alvr_sockets"
version = "16.0.0-rc2"
authors = ["alvr-org", "Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
# Serialization
bincode = "1"
serde = { version = "1", features = ["derive"] }
# Async and networking
bytes = "1"
futures = "0.3"
governor = "0.3"
nonzero_ext = "0.2"
tokio = { version = "1", features = ["rt", "net", "macros"] }
tokio-util = { version = "0.6", features = ["codec", "net"] }
# Miscellaneous
alvr_common = { path = "../common" }
nalgebra = { version = "0.28", features = ["serde-serialize"] }
rand = "0.8"
rcgen = "0.8"
semver = { version = "1", features = ['serde'] }
