[package]
name = "alvr_audio"
version = "16.0.0-rc2"
authors = ["alvr-org", "Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
parking_lot = "0.11"
lazy_static = "1"
serde = "1"
tokio = { version = "1" }
alvr_common = { path = "../common" }
cpal = "0.13"
rodio = "0.14"
