[package]
name = 'alvr_common'
version = '11.0.0-alpha.0'
authors = ['Riccardo Zaglia <riccardo.zaglia5@gmail.com>']
license = 'MIT'
edition = '2018'

[dependencies]
semver = '^0.9.0'
serde = { version = '^1.0', features = ['derive'] }
serde_json = '^1.0'
log = '^0.4.8'
backtrace = '^0.3.46'
settings-schema = { git = 'https://github.com/zarik5/settings-schema-rs', features = ['rename_camel_case'] }
sysinfo = '^0.14.1'

[build-dependencies]
alvr_xtask = { path = '../xtask' }