[package]
name = "alvr_common"
version = "1.0.0"
authors = ["alvr-org", "Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2018"

[features]
default = []
nightly = []

[dependencies]
lazy_static = "1"
semver = { version = "0.11", features = ['serde'] }
log = "0.4"
backtrace = "0.3"
rand = "0.7"
settings-schema = { git = "https://github.com/zarik5/settings-schema-rs", features = ["rename_camel_case"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = "1"
futures = "0.3"
tokio = { version = "0.2", features = ["net"] }
tokio-util = { version = "0.3", features = ["codec"] }
rcgen = "0.8"
gfx-hal = "0.6"
# cpal = { git = "https://github.com/RustAudio/cpal" }

[target.'cfg(not(target_os = "android"))'.dependencies]
dirs = "3"
sysinfo = "0.15"
runas = "0.2"
msgbox = { git = 'https://github.com/bekker/msgbox-rs' }

[target."cfg(windows)".dependencies]
winapi = { version = "0.3", features = [
    "mmdeviceapi",
    "propsys",
    "coml2api",
    "propidl",
    "functiondiscoverykeys_devpkey",
    "wtypes",
    "objbase",
] }
wio = "0.2"
widestring = "0.4"
winreg = "0.7"
gfx-backend-dx11 = "0.6"

[build-dependencies]
alvr_xtask = { path = "../xtask" }
