[package]
name = "alvr_common"
version = "16.0.0-rc2"
authors = ["alvr-org", "Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2018"

[features]
nightly = []

[dependencies]
# Basic utilities
lazy_static = "1"
parking_lot = "0.11"
# Logging
backtrace = "0.3"
log = "0.4"
# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
settings-schema = { path = "../settings-schema", features = [
    "rename_camel_case",
] }
# Miscellaneous
alvr_filesystem_layout = { path = "../filesystem_layout" }
encoding_rs_io = "0.1"
rand = "0.8"
semver = { version = "1", features = ['serde'] }

[target.'cfg(not(target_os = "android"))'.dependencies]
dirs = "3"
msgbox = "0.6"
runas = "0.2"
