[package]
name = 'alvr_common'
version = '12.0.0'
authors = ['Riccardo Zaglia <riccardo.zaglia5@gmail.com>']
license = 'MIT'
edition = '2018'

[dependencies]
regex = '^1.3.9'
semver = '^0.10.0'
serde = { version = '^1.0', features = ['derive'] }
serde_json = '^1.0'
log = '^0.4.8'
backtrace = '^0.3.46'
settings-schema = { git = 'https://github.com/zarik5/settings-schema-rs', features = ['rename_camel_case'] }
sysinfo = '^0.15.0'
runas = '^0.2.1'
gfx-hal = '^0.6.0'
# cpal = { git = 'https://github.com/RustAudio/cpal' }

[target.'cfg(windows)'.dependencies]
winapi = { version = '^0.3.8', features = [
    'mmdeviceapi',
    'propsys',
    'coml2api',
    'propidl',
    'functiondiscoverykeys_devpkey',
    'wtypes',
    'objbase',
] }
wio = '^0.2.2'
widestring = '^0.4.2'
winreg = '^0.7.0'
gfx-backend-dx11 = '^0.6.8'

[build-dependencies]
alvr_xtask = { path = '../xtask' }
