[package]
name = 'alvr_web_server'
version = '11.0.0-alpha.0'
authors = ['Riccardo Zaglia <riccardo.zaglia5@gmail.com>']
license = 'MIT'
edition = '2018'

[dependencies]
alvr_common = { path = '../common' }
tokio = '^0.2.19'
warp = '^0.2.2'

[build-dependencies]
serde_json = '1.0'
alvr_common = { path = '../common' }
