[package]
name = 'alvr_web_server'
version = '12.1.0'
authors = ['Riccardo Zaglia <riccardo.zaglia5@gmail.com>']
license = 'MIT'
edition = '2018'

[dependencies]
serde = '^1.0' 
serde_json = '^1.0' 
bincode = '^1.2.1' 
settings-schema = { git = 'https://github.com/zarik5/settings-schema-rs' } 
futures = '^0.3.5' 
bytes = '^0.5.0'
tokio = { version = '^0.2.20', features = ['macros', 'process', 'io-util', 'stream', 'udp', 'fs'] } 
tokio-util = { version = '^0.3.0', features = ['codec'] } 
tokio-tungstenite = '^0.11.0'
headers = '^0.3.2'
hyper = '^0.13.8' 
log = '^0.4.8' 
chrono = '^0.4.11' 
fern = '^0.6.0' 
msgbox = { git = 'https://github.com/bekker/msgbox-rs' } 
alvr_common = { path = '../common' } 
single-instance = '^0.1.2' 
ipconfig = '^0.2.2' #todo: remove crate and get ip during handshake
webbrowser = '^0.5.5' 

[build-dependencies]
serde_json = '^1.0'
alvr_common = { path = '../common' }
