[package]
name = "alvr_web_server"
version = "12.1.0"
authors = ["Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
serde = "1" 
serde_json = "1" 
bincode = "1.3" 
settings-schema = { git = "https://github.com/zarik5/settings-schema-rs" } 
futures = "0.3" 
bytes = "0.5" 
tokio = { version = "0.2", features = ["macros", "process", "io-util", "stream", "udp", "fs"] } 
tokio-util = { version = "0.3", features = ["codec"] } 
tokio-tungstenite = "0.11" 
headers = "0.3" 
hyper = "0.13" 
log = "0.4" 
chrono = "0.4" 
fern = "0.6" 
msgbox = { git = "https://github.com/bekker/msgbox-rs" } 
alvr_common = { path = "../common" } 
single-instance = "0.1" 
ipconfig = "0.2" #todo: remove crate and get ip during handshake
webbrowser = "0.5" 

[build-dependencies]
serde_json = "1"
alvr_common = { path = "../common" }
