[package]
name = "openvr-driver-sys"
version = "0.1.0+1.16.8"
authors = ["Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2021"
rust-version = "1.56"

[build-dependencies]
bindgen = "0.59"
cc = "1"
regex = "1"
