[package]
name = "openvr-driver-sys"
version = "0.1.0+1.16.8"
authors = ["Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2018"

[build-dependencies]
bindgen = "0.57"
cc = "1.0"
regex = "1.3"
