[package]
name = "alvr_filesystem"
version = "17.0.0-dev.1"
authors = ["alvr-org", "Patrick Nicolas <patricknicolas@laposte.net>"]
license = "MIT"
edition = "2021"
rust-version = "1.56"

[dependencies]
lazy_static = "1"
dirs = "4"
