[package]
name = "alvr_xtask"
version = "1.0.0"
authors = ["alvr-org", "Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
# Basic utilities
chrono = "0.4"
lazy_static = "1"
rand = "0.8"
regex = "1"
# File system
dirs = "3"
fs_extra = "1"
toml_edit = "0.2"
walkdir = "2"
zip = "0.5"
# Miscellaneous
pico-args = "0.4"
runas = "0.2"
semver = "0.11"
ureq = "2"
