[package]
name = "alvr_xtask"
version = "1.0.0"
authors = ["alvr-org", "Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
fs_extra = "1"
pico-args = "0.4"
walkdir = "2"
